baseURL: https://tech-conferences.com
languageCode: en-us
theme: conferences
enableGitInfo: true

params:
  title: Awesome Tech Conferences
  description: This is an open-source and curated list of upcoming technology conferences.
  truncateAt: 285
  repo:
    url: https://github.com/ThorstenHans/awesome-tech-conferences
  author:
    name: Thorsten Hans
    url: https://www.thorsten-hans.com
    location: Saarland
