name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  lint_conference_data:
    runs-on: ubuntu-latest
    name: Lint Conference Data
    steps:
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: confs-*.yaml
          config_file: .yamllint
  generate_readme:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: lint_conference_data
    name: Generate README.md
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - name: Compile Awesome Readme Generator
        working-directory: ./tools/awesome-readme-generator
        run: make build && make copy-to-repo-root
      - name: Generate Conferences data file
        run: make build-confs
      - name: Generate README.md
        run: |
          ./awesome-readme --template ./confs.tmpl --data ./data/confs.yaml --readme-template ./README.tmpl --output ./README.md
      - name: Commit & Push README.md
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Thorsten Hans'
            git config --global user.email 'ThorstenHans@users.noreply.github.com'
            git add README.md
            git commit -am "docs(*): Generate README for ${{ github.sha }}" -m "[skip actions]"
            git push
          fi

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    needs: lint_conference_data
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: webiny/action-conventional-commits@v1.1.0
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./themes/conferences
      - name: Build CSS
        run: npm run build
        working-directory: ./themes/conferences
      - name: Generate Conferences data file
        run: make build-confs
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_0FAE23503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_0FAE23503 }}
          action: "close"
